### ISSUE TITLE
aruco and deep distance when landing

### ISSUE THREAD

**Issue by liuxibo** [yankailab/OpenKAI#31]
I have some questions to ask.
https://github.com/yankailab/OpenKAI/blob/d1c11abba0c3b623e9f98f37769bc51f5b8ea5cc/src/Autopilot/Controller/APcopter/APcopter_arucoLanding.cpp#L135
Whether this distance needs to be calculated with the position of the Target ?

Thank you!

**Comment by yankailab** [comment]
No this distance is just the altitude to ground, which changes according to vehicle’s attitude. NOT the distance to target.

**Comment by yankailab** [comment]
will do

**Comment by yankailab** [comment]
Hello, OpenKAI added its own precision landing instead of using the Ardupilot LAND mode.
The new precision landing is supposed to work in Ardupilot GUIDED mode. It navigate the vehicle to land on a ground target with a constant speed controller, therefore the distance to target is not necessary.

This new mode is specially useful in a place with full of aptitude gaps where the downward altimeters would change frequently causing instability, e.g. car roof, dense house area, narrow bridge.

For more information please refer to:
https://github.com/yankailab/OpenKAI/blob/master/src/Autopilot/Controller/APcopter/APcopter_land.cpp

Some demo videos (might be) provided later when our YouTube channel is ready.
Cheers.
